apiVersion: v1
kind: Secret
metadata:
  name: postgres-config
type: Opaque
stringData:
  user-name: postgresadmin
  password: admin123
  database-name: postgresdb
  db-url: jdbc:postgresql://3.109.191.110:31496/postgresdb